pimwatch 2018-12-21 02:58:37,533:INFO live sg refreshed: 23.212.185.5->232.10.1.1
pimwatch 2018-12-21 02:59:37,948:INFO live sg refreshed: 23.212.185.5->232.1.1.1
pimwatch 2018-12-21 02:59:37,949:INFO live sg refreshed: 23.212.185.5->232.10.1.1
pimwatch 2018-12-21 03:00:37,340:INFO live sg refreshed: 23.212.185.5->232.1.1.1
pimwatch 2018-12-21 03:00:37,341:INFO live sg refreshed: 23.212.185.5->232.10.1.1
pimwatch 2018-12-21 03:01:37,756:INFO live sg refreshed: 23.212.185.5->232.1.1.1
pimwatch 2018-12-21 03:01:37,757:INFO live sg refreshed: 23.212.185.5->232.10.1.1
pimwatch 2018-12-21 03:02:27,932:INFO removing live sg: 23.212.185.5->232.10.1.1
pimwatch 2018-12-21 03:02:27,932:INFO stopping sg 23.212.185.5->232.10.1.1
pimwatch-join-23.212.185.5-232.10.1.1
pimwatch 2018-12-21 03:02:30,702:INFO stopped container: CompletedProcess(args=['/snap/bin/docker', 'container', 'stop', 'pimwatch-join-23.212.185.5-232.10.1.1'], returncode=0)
pimwatch 2018-12-21 03:02:30,704:INFO removing 23.212.185.5->232.10.1.1 from gw gw(18.144.22.247):2
Traceback (most recent call last):
  File "./pimwatch.py", line 640, in <module>
    retval = main(sys.argv)
  File "./pimwatch.py", line 635, in main
    channels.remove_sg(sg)
  File "./pimwatch.py", line 614, in remove_sg
    self.stop_sg(live_sg)
  File "./pimwatch.py", line 533, in stop_sg
    if other.source == sg.source:
AttributeError: 'tuple' object has no attribute 'source'
user@ingest-rtr:~$ tcpdump: Unable to write output: Broken pipe


